# Generated by Django 4.1.7 on 2023-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularuserview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='exam_id',
            field=models.CharField(max_length=50),
        ),
    ]
