# Generated by Django 4.1.7 on 2023-08-01 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_id_fieldofstudy_course_unique_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_remove_options_solution_image_and_more'),
        ('regularuserview', '0002_alter_userresponse_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseddate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_dates', to='user.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='purchaseddate',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_dates', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='purchaseddate',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_dates', to='regularuserview.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='purchased_profiles', to='user.fieldofstudy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='purchased_exams',
            field=models.ManyToManyField(blank=True, related_name='purchased_profiles', to='exam.exam'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
