# Generated by Django 4.1.7 on 2023-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularuserview', '0003_purchaseddate_course_purchaseddate_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='exam_name',
            field=models.CharField(default='test-1', max_length=150),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='qualify_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='time_taken',
            field=models.CharField(default='00:00:00', max_length=30),
        ),
    ]
