# Generated by Django 4.1.7 on 2023-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularuserview', '0004_userresponse_exam_name_userresponse_qualify_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='exam_name',
            field=models.TextField(default='test-1'),
        ),
    ]
