# Generated by Django 4.2.5 on 2024-01-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularuserview', '0005_alter_userresponse_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='marks_scored',
            field=models.CharField(default='00', max_length=50),
        ),
    ]
