# Generated by Django 4.2.5 on 2024-05-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularuserview', '0006_alter_userresponse_marks_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseddate',
            name='isPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='purchaseddate',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseddate',
            name='order_payment_id',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
