# Generated by Django 4.2.3 on 2024-08-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularuserview', '0007_purchaseddate_ispaid_purchaseddate_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='total_scored',
            field=models.CharField(default='00', max_length=500),
        ),
    ]
