# Generated by Django 4.1.7 on 2023-07-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourses',
            name='course',
        ),
        migrations.AddField(
            model_name='popularcourses',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.fieldofstudy'),
        ),
    ]
