# Generated by Django 4.1.7 on 2023-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_popularcourses_course_popularcourses_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularcourses',
            name='course',
        ),
        migrations.AddField(
            model_name='popularcourses',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='user.fieldofstudy'),
        ),
    ]
