# Generated by Django 4.1.7 on 2023-07-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_popularcourses_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldofstudy',
            old_name='id',
            new_name='course_unique_id',
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='field_of_study',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='slug_studyfield',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
