# Generated by Django 4.1.7 on 2023-08-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_id_fieldofstudy_course_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesnested',
            name='pdf_link',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
