# Generated by Django 4.1.7 on 2023-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_pdf_link_notesnested_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesnested',
            name='slug_notes',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
