# Generated by Django 4.1.7 on 2023-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_notesnested_slug_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosnested',
            name='video_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
