# Generated by Django 4.1.7 on 2023-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_videosnested_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
