# Generated by Django 4.1.7 on 2023-08-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_modules_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
