# Generated by Django 4.2.5 on 2024-05-21 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_abstractotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularusermodel',
            name='count',
            field=models.IntegerField(default=0, help_text='Number of otp sent'),
        ),
        migrations.AddField(
            model_name='regularusermodel',
            name='otp_session_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='regularusermodel',
            name='otps',
            field=models.CharField(blank=True, default='000000', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='regularusermodel',
            name='verified',
            field=models.BooleanField(default=False, help_text='If otp verification got successful'),
        ),
        migrations.AlterField(
            model_name='regularusermodel',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
