# Generated by Django 4.2.3 on 2024-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_regularusermodel_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='Course_duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
