# Generated by Django 4.1.7 on 2023-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='multiselect',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='numericals',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
