# Generated by Django 4.1.7 on 2023-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_option1_multiplechoice_option1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='solution_image',
        ),
        migrations.RemoveField(
            model_name='options',
            name='solution_text',
        ),
        migrations.AddField(
            model_name='multiselect',
            name='solution_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='multiselect',
            name='solution_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
