# Generated by Django 4.2.3 on 2023-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_options_solution_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='option1_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='option2_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='option3_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='option4_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
