# Generated by Django 4.2.7 on 2023-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_multiplechoice_option1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='option1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='option2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='option3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='option4_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiselect',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numericals',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='options_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
