# Generated by Django 4.2.3 on 2024-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_exam_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='sessions',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
