# Generated by Django 4.2.3 on 2024-05-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_exam_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='sessions',
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='multiselect',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='numericals',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
