# Generated by Django 4.2.3 on 2024-06-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_exam_sessions_multiplechoice_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='solution_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='solution_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='solution_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='solution_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='multiselect',
            name='solution_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='numericals',
            name='solution_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='options',
            name='solution_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pdfs/'),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_no', models.CharField(max_length=300)),
                ('section_name', models.CharField(blank=True, max_length=400, null=True)),
                ('positive_marks', models.FloatField(default=0.0)),
                ('negetive_mark', models.FloatField(default=0.0)),
                ('no_of_ques_to_be_validated', models.IntegerField()),
                ('exam_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exam.exam')),
            ],
        ),
    ]
