# Generated by Django 4.2.3 on 2024-06-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_exam_solution_image_exam_solution_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiplechoice', to='exam.sections'),
        ),
        migrations.AlterField(
            model_name='multiselect',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiselect', to='exam.sections'),
        ),
        migrations.AlterField(
            model_name='numericals',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numericals', to='exam.sections'),
        ),
    ]
