# Generated by Django 4.2.3 on 2024-06-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_multiplechoice_section_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sections',
            constraint=models.UniqueConstraint(fields=('exam_name', 'section_no'), name='unique_section_no_per_exam'),
        ),
    ]
