# Generated by Django 4.2.3 on 2024-06-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_sections_unique_section_no_per_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='options',
            constraint=models.UniqueConstraint(fields=('question', 'option_no'), name='unique_option_no_per_question'),
        ),
    ]
