# Generated by Django 4.2.3 on 2024-08-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_sections_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
